# Generated by Django 5.1.5 on 2025-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_borrowing_approved_by_alter_borrowing_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('pending_purchase', 'Pending Purchase Approval'), ('payment_pending', 'Payment Pending'), ('purchased', 'Purchased'), ('rejected_purchase', 'Rejected Purchase'), ('payment_failed', 'Payment Failed')], default='pending_purchase', max_length=20),
        ),
    ]
