# Generated by Django 5.1.5 on 2025-06-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_borrowing_amount_borrowing_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book Item', 'verbose_name_plural': 'Book Stock'},
        ),
        migrations.AlterModelOptions(
            name='borrowing',
            options={'verbose_name': 'Purchase Transaction', 'verbose_name_plural': 'Purchase Transactions'},
        ),
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name': 'Library Staff Member', 'verbose_name_plural': 'Library Staff'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Patron', 'verbose_name_plural': 'Patrons'},
        ),
    ]
